// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XbimFloorPlanGenerator.Data;

namespace XbimFloorPlanGenerator.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191111094827_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ElevationOfTerrain")
                        .HasColumnType("float");

                    b.Property<string>("EntityLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Building");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.ProductShape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BoundingBoxSizeX")
                        .HasColumnType("float");

                    b.Property<double>("BoundingBoxSizeY")
                        .HasColumnType("float");

                    b.Property<double>("BoundingBoxX")
                        .HasColumnType("float");

                    b.Property<double>("BoundingBoxY")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ShapeType")
                        .HasColumnType("int");

                    b.Property<int?>("WallId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WallId");

                    b.ToTable("ProductShape");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectSet");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("IfcId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfcName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Wall");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Building", b =>
                {
                    b.HasOne("XbimFloorPlanGenerator.Data.Entities.Site", null)
                        .WithMany("Buildings")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Floor", b =>
                {
                    b.HasOne("XbimFloorPlanGenerator.Data.Entities.Building", null)
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.ProductShape", b =>
                {
                    b.HasOne("XbimFloorPlanGenerator.Data.Entities.Wall", null)
                        .WithMany("ProductShapes")
                        .HasForeignKey("WallId");
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Site", b =>
                {
                    b.HasOne("XbimFloorPlanGenerator.Data.Entities.Project", null)
                        .WithMany("Sites")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XbimFloorPlanGenerator.Data.Entities.Wall", b =>
                {
                    b.HasOne("XbimFloorPlanGenerator.Data.Entities.Floor", null)
                        .WithMany("Walls")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
